name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: cmake -B build -S . -DGLTF_BUILD_TEST=ON
    - name: make
      run: make -C build
    - name: test
      run: make test -C build
#    - name: make distcheck
#      run: make distcheck
